apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app-config
  labels:
    app.kubernetes.io/name: python-demo-app
data:
  APP_NAME: "python-demo-app"
  APP_VERSION: "0.1.0"
  ENVIRONMENT: "kubernetes"
  LOG_LEVEL: "INFO"